{% set name = "PyCardioTest" %}
{% set version = "0.0.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://test.pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 04308d93d023c157d191cc489d8c0ae9b4342f366a5e3134c9f264d49ff6fac8

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - matplotlib
    - numpy
    - pip
    - python
    - scipy
  run:
    - matplotlib
    - numpy
    - python
    - scipy

test:
  imports:
    - PyCardio
    - PyCardio.ECG
    - PyCardio.HRT
    - PyCardio.HRV
    - PyCardio.ReadHolter

about:
  home: https://github.com/javierfm27/PyCardio
  license: MIT
  license_family: MIT
  license_file: 
  summary: Package for heart analysis
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
